# Generated by Django 5.1.4 on 2025-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grams',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight of the product in grams', max_digits=5),
        ),
    ]
